name: Nagarjun Palavalli > Entrepreneur • Web Developer and Designer
url: http://www.nagarjun.co/
author: Nagarjun Palavalli
copyright: Nagarjun Palavalli

markdown: redcarpet
pygments: true

regeneration: -w
